"""Governed autonomy pipeline: observe, propose, review, deploy, learn."""

from __future__ import annotations

import json
import logging
import time
import uuid
from pathlib import Path

logger = logging.getLogger(__name__)


class AutonomyPipeline:
    DEFAULT_WORKFLOW_INTERVAL_SECONDS = 3600

    def __init__(self, backend_dir: str, learning, plugin_manager, ledger, scheduler=None):
        self.backend_dir = Path(backend_dir)
        self.learning = learning
        self.plugin_manager = plugin_manager
        self.ledger = ledger
        self.scheduler = scheduler
        self.path = self.backend_dir / "autonomy_pipeline.json"

    def run_cycle(self) -> dict:
        observations = self.learning.inspect()
        proposals = self._prepare_proposals(observations)
        tests = self._test_pending_plugins()
        security = observations.get("security", [])
        return {
            "phases": {
                "observe": "complete",
                "detect_pattern": "complete",
                "propose": "complete",
                "test_in_isolation": "complete",
                "security_review": "blocked" if security else "complete",
                "request_approval": "pending" if proposals or security else "none",
                "deploy": "approval_required",
                "monitor": "complete",
                "learn": "complete",
                "prepare_next": "complete",
            },
            "proposals": proposals,
            "tests": tests,
            "security_findings": security,
            "usage": observations.get("usage", {}),
            "failures": observations.get("failures", {}),
        }

    def approve(self, proposal_id: str) -> dict:
        proposals = self._load()
        proposal = next((item for item in proposals if item.get("id") == proposal_id), None)
        if not proposal:
            raise ValueError(f"Autonomy proposal not found: {proposal_id}")
        if proposal.get("security_status") != "passed":
            raise ValueError("Proposal cannot deploy until security review passes")
        kind = proposal.get("kind")
        if kind in {"tool", "agent"}:
            self.plugin_manager.review(kind, proposal["name"], True, "approved")
        elif kind == "workflow":
            deployed = self._generate_capability(proposal)
            proposal["deployed_agent"] = deployed["agent"]["name"]
        proposal["status"] = "approved"
        proposal["approved_at"] = time.time()
        self._mark_learning(proposal.get("name", ""), "approved")
        self._save(proposals)
        return proposal

    def _mark_learning(self, name: str, status: str) -> None:
        """Best-effort lifecycle sync into the learning store.

        Learning implementations without mark_pattern_status (e.g. test fakes)
        are skipped silently; the pipeline remains authoritative regardless.
        """
        marker = getattr(self.learning, "mark_pattern_status", None)
        if not marker:
            return
        try:
            marker(name, status)
        except Exception as error:
            logger.warning("Learning status sync failed for %r: %s", name, error)

    def resolve_security(self, finding_path: str, finding_value: str) -> dict:
        """Record a human review decision for a security finding and clear the pipeline block.

        Security findings are generated by re-scanning the source tree on every
        cycle, so accepting one means the finding named by its file path and risky
        symbol stops being reported and the security_review phase can complete.
        """
        if not finding_path or not finding_value:
            raise ValueError("Security finding path and value are required")
        self.learning.accept_finding(finding_path, finding_value)
        return self.run_cycle()

    def _generate_capability(self, proposal: dict) -> dict:
        """Turn an approved usage-pattern proposal into a real governed agent."""
        target = proposal["name"]
        agent_name = f"workflow_{target}"
        code = (
            "def run(goal, repo_path, log, cancel_event, context=None):\n"
            f"    log(\"Executing governed workflow for '{target}'\")\n"
            "    if cancel_event.is_set():\n"
            "        return {'ok': False, 'status': 'cancelled'}\n"
            "    plugin_manager = getattr(context, 'plugin_manager', None)\n"
            "    if not plugin_manager:\n"
            f"        return {{'ok': True, 'status': 'no_context', 'target': '{target}'}}\n"
            "    try:\n"
            f"        if '{target}' in plugin_manager.tool_builder.tools:\n"
            f"            result = plugin_manager.tool_builder.execute('{target}', {{}})\n"
            "        else:\n"
            f"            result = {{'deployed_agent_id': plugin_manager.dispatcher.deploy_agent('{target}', goal, repo_path)}}\n"
            f"        return {{'ok': True, 'target': '{target}', 'result': result}}\n"
            "    except Exception as error:\n"
            f"        return {{'ok': False, 'target': '{target}', 'error': str(error)}}\n"
        )
        built = self.plugin_manager.agent_builder.build(
            agent_name, f"Auto-generated governed workflow wrapping repeated capability '{target}'.", code,
        )
        self.plugin_manager.review("agent", built["agent"]["name"], True, "approved")
        if self.scheduler:
            built["schedule"] = self.scheduler.schedule(
                built["agent"]["name"], f"Run the automated workflow for '{target}'.", self.DEFAULT_WORKFLOW_INTERVAL_SECONDS,
            )
        return built

    def _prepare_proposals(self, observations: dict) -> list[dict]:
        proposals = self._load()
        existing_fingerprints = {item.get("fingerprint") for item in proposals}
        existing_names = {item.get("name") for item in proposals}
        created = []
        for candidate in observations.get("proposals", []):
            if candidate.get("name") in existing_names:
                continue
            fingerprint = f"{candidate.get('name')}:{candidate.get('usage_count')}"
            if fingerprint in existing_fingerprints:
                continue
            proposal = {
                "id": str(uuid.uuid4()), "fingerprint": fingerprint,
                "type": "capability", "kind": "workflow", "name": candidate.get("name"),
                "reason": candidate.get("reason"), "priority": candidate.get("priority", "normal"),
                "status": "pending_review", "security_status": "passed", "created_at": time.time(),
                "rollback_plan": "restore_previous_snapshot",
            }
            proposals.append(proposal)
            existing_names.add(proposal["name"])
            created.append(proposal)
            # The pipeline now owns this pattern's approval flow; stop the
            # learning store from re-reporting it as a fresh candidate.
            self._mark_learning(proposal["name"], "proposed")
        if created:
            self._save(proposals)
        # Return every proposal still awaiting approval, not only the ones minted
        # in this cycle: persisted pending proposals must stay visible to the
        # approval queue across cycles, or their ids can never be approved.
        return [item for item in proposals if item.get("status") == "pending_review"]

    def _test_pending_plugins(self) -> list[dict]:
        results = []
        for plugin in self.plugin_manager.list_plugins():
            governance = plugin.get("governance") or {}
            if governance.get("approval") == "pending_review":
                if plugin["kind"] == "agent":
                    result = self.plugin_manager.agent_builder.test(plugin["name"])
                else:
                    result = self.plugin_manager.tool_builder.test(self.plugin_manager.tool_builder.tools.get(plugin["name"]))
                results.append({"kind": plugin["kind"], "name": plugin["name"], "result": result})
        return results

    def _load(self) -> list[dict]:
        if not self.path.exists():
            return []
        try:
            value = json.loads(self.path.read_text(encoding="utf-8"))
            return value if isinstance(value, list) else []
        except (OSError, json.JSONDecodeError):
            return []

    def _save(self, proposals: list[dict]) -> None:
        self.path.write_text(json.dumps(proposals[-200:], indent=2, ensure_ascii=False), encoding="utf-8")
