# Generated by Friday's verified custom-tool builder.
TOOL_MANIFEST = {'name': 'forceupdatechecker', 'version': '1.0.0', 'enabled': True, 'description': 'A tool to check for Windows updates using a non-destructive, read-only PowerShell command.', 'operation': 'readonly_powershell', 'parameters': {}, 'config': {}, 'governance': {'approval': 'pending_review', 'permissions': ['readonly_powershell'], 'dependencies': [], 'resource_limits': {'timeout_seconds': 60, 'max_memory_mb': 256, 'max_output_chars': 6000}, 'test_fixtures': {}, 'security_review': 'pending', 'rollback_plan': 'restore_previous_snapshot', 'expires_at': None, 'score': {'successes': 0, 'failures': 0}}}

def describe():
    return TOOL_MANIFEST.copy()
