# Generated by Friday's verified custom-tool builder.
TOOL_MANIFEST = {'name': 'money_exchange', 'description': 'Converts an amount from one currency to another using mock exchange rates.', 'operation': 'python_module', 'parameters': {'from_currency': {'description': 'The source currency code (e.g., USD, EUR).', 'type': 'string'}, 'to_currency': {'description': 'The target currency code (e.g., ZAR, GBP).', 'type': 'string'}, 'amount': {'type': 'number', 'description': 'The amount to exchange.'}}, 'config': {}}

def describe():
    return TOOL_MANIFEST.copy()

import json

def run(arguments):
    try:
        amount = arguments.get("amount")
        from_currency = arguments.get("from_currency").upper()
        to_currency = arguments.get("to_currency").upper()

        # In a real scenario, this would call an exchange rate API.
        # For this prototype, we'll use mock rates.
        # Example rates relative to a base currency (e.g., USD)
        mock_rates = {
            "USD": 1.0,
            "EUR": 0.92,
            "GBP": 0.79,
            "ZAR": 18.75
        }

        if from_currency not in mock_rates or to_currency not in mock_rates:
            print(json.dumps({"error": "Unsupported currency in mock rates."}))
            return

        # Convert amount to base currency, then to target currency
        amount_in_base = amount / mock_rates[from_currency]
        converted_amount = amount_in_base * mock_rates[to_currency]

        print(json.dumps({
            "amount": amount,
            "from_currency": from_currency,
            "to_currency": to_currency,
            "converted_amount": round(converted_amount, 2),
            "note": "Exchange rates are mocked for this custom tool prototype."
        }))
    except Exception as e:
        print(json.dumps({"error": str(e)}))

if __name__ == '__main__':
    import json
    arguments = json.loads(input())
    if 'run' in locals():
        output = run(arguments)
        if output is not None:
            print(json.dumps(output))
