# Generated by Friday's verified custom-tool builder.
TOOL_MANIFEST = {'name': 'safeupdatechecker', 'version': '1.0.0', 'enabled': True, 'description': 'A read-only PowerShell tool to check for available Windows updates without installing or modifying the system.', 'operation': 'readonly_powershell', 'parameters': {}, 'config': {}, 'governance': {'approval': 'pending_review', 'permissions': ['readonly_powershell'], 'dependencies': [], 'resource_limits': {'timeout_seconds': 60, 'max_memory_mb': 256, 'max_output_chars': 6000}, 'test_fixtures': {}, 'security_review': 'pending', 'rollback_plan': 'restore_previous_snapshot', 'expires_at': None, 'score': {'successes': 0, 'failures': 0}}}

def describe():
    return TOOL_MANIFEST.copy()
