# Generated by Friday's verified agent builder.
AGENT_MANIFEST = {'name': 'windows_update_checker', 'version': '1.0.0', 'enabled': True, 'description': 'An agent that automatically checks for Windows updates using PowerShell and returns detailed results.', 'parameters': {}}

import subprocess
import json

def run(goal, repo_path, log, cancel_event):
    log("Starting comprehensive Windows Update check agent.")
    try:
        # This is a conceptual command as actual update checks are complex and environment-dependent.
        # A realistic approach might involve PSWindowsUpdate module, which isn't guaranteed.
        # We will execute a simple check and capture stdout/stderr.
        command = "powershell.exe -Command 'Get-WindowsUpdate 2>&1'"

        process = subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, shell=True)
        stdout, stderr = process.communicate(timeout=300)

        if cancel_event.is_set():
            return "Check cancelled."

        # Capture and structure output
        report = {"status": "Completed", "stdout": stdout, "stderr": stderr, "note": "Actual update retrieval and installation requires specific permissions and modules (like PSWindowsUpdate) which may not be configured."}
        
        log("Windows Update check process finished and results captured.")
        return json.dumps(report, indent=2)

    except Exception as e:
        log(f"An error occurred: {e}")
        return json.dumps({"status": "Error", "error": str(e)}, indent=2)
