# Generated by Friday's verified agent builder.
AGENT_MANIFEST = {'name': 'workflow_browser_control', 'version': '1.0.0', 'enabled': True, 'description': "Auto-generated governed workflow wrapping repeated capability 'browser_control'.", 'parameters': {}, 'governance': {'approval': 'pending_review', 'permissions': [], 'dependencies': [], 'resource_limits': {'timeout_seconds': 60, 'max_memory_mb': 256, 'max_output_chars': 6000}, 'test_fixtures': {}, 'security_review': 'pending', 'rollback_plan': 'restore_previous_snapshot', 'expires_at': None, 'score': {'successes': 0, 'failures': 0}}}

def run(goal, repo_path, log, cancel_event, context=None):
    log("Executing governed workflow for 'browser_control'")
    if cancel_event.is_set():
        return {'ok': False, 'status': 'cancelled'}
    plugin_manager = getattr(context, 'plugin_manager', None)
    if not plugin_manager:
        return {'ok': True, 'status': 'no_context', 'target': 'browser_control'}
    try:
        if 'browser_control' in plugin_manager.tool_builder.tools:
            result = plugin_manager.tool_builder.execute('browser_control', {})
        else:
            result = {'deployed_agent_id': plugin_manager.dispatcher.deploy_agent('browser_control', goal, repo_path)}
        return {'ok': True, 'target': 'browser_control', 'result': result}
    except Exception as error:
        return {'ok': False, 'target': 'browser_control', 'error': str(error)}
