"""Infrastructure-as-Code layer for FRIDAY — Terraform/CloudFormation generation, cloud provisioning, Kubernetes management."""
from __future__ import annotations
import json, hashlib, time
from pathlib import Path

_BACKEND = Path(__file__).resolve().parent.parent
_STATE = _BACKEND / "long_term_memory" / "infra_stacks.json"

def _load() -> dict:
    try:
        return json.loads(_STATE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"stacks": {}}

def _save(state: dict) -> None:
    _STATE.parent.mkdir(parents=True, exist_ok=True)
    _STATE.write_text(json.dumps(state, indent=2), encoding="utf-8")

def generate_terraform(provider: str, region: str, resources: list, stack_name: str) -> dict:
    """Generate a Terraform HCL module from a resource spec list."""
    hcl = [
        'terraform {\n  required_providers {\n    %s = {\n      source  = "hashicorp/%s"\n    }\n  }\n}\n' % (provider, provider),
        'provider "%s" {\n  region = "%s"\n}\n' % (provider, region),
    ]
    for i, r in enumerate(resources or []):
        rtype = r.get("type", "instance"); rname = r.get("name", "res_%d" % i)
        if rtype in ("instance", "ec2", "vm", "compute"):
            if provider == "aws":
                hcl.append('resource "aws_instance" "%s" {\n  ami           = "%s"\n  instance_type = "%s"\n  tags = { Name = "%s" }\n}\n' % (rname, r.get("ami", "ami-0c55b159cbfafe1f0"), r.get("size", "t3.micro"), rname))
            elif provider == "gcp":
                hcl.append('resource "google_compute_instance" "%s" {\n  name         = "%s"\n  machine_type = "%s"\n  zone         = "%s-a"\n  boot_disk { initialize_params { image = "%s" } }\n  network_interface { network = "default" }\n}\n' % (rname, rname, r.get("size", "e2-micro"), region, r.get("image", "debian-cloud/debian-12")))
            elif provider == "azure":
                hcl.append('resource "azurerm_linux_virtual_machine" "%s" {\n  name                  = "%s"\n  size                  = "%s"\n}\n' % (rname, rname, r.get("size", "Standard_B1s")))
        elif rtype in ("db", "rds", "database"):
            hcl.append('resource "aws_db_instance" "%s" {\n  identifier     = "%s"\n  engine         = "%s"\n  instance_class = "%s"\n  allocated_storage = %d\n  skip_final_snapshot = true\n}\n' % (rname, rname, r.get("engine", "postgres"), r.get("size", "db.t3.micro"), int(r.get("storage_gb", 20))))
        elif rtype in ("cdn", "cloudfront"):
            hcl.append('resource "aws_cloudfront_distribution" "%s" {\n  enabled = true\n  default_cache_behavior {\n    allowed_methods = ["GET", "HEAD"]\n    target_origin_id = "%s-origin"\n    viewer_protocol_policy = "redirect-to-https"\n  }\n}\n' % (rname, rname))
        else:
            hcl.append('# TODO: unsupported resource %s/%s for %s\n' % (provider, rtype, rname))
    return {"ok": True, "provider": provider, "region": region, "stack": stack_name, "hcl": "\n".join(hcl)}

def generate_cloudformation(stack_name: str, resources: list) -> dict:
    """Generate an AWS CloudFormation template from resources."""
    template = {"AWSTemplateFormatVersion": "2010-09-09", "Description": "Generated by FRIDAY for %s" % stack_name, "Resources": {}}
    for i, r in enumerate(resources or []):
        rid = "FridayRes%d" % i
        if r.get("type") in ("instance", "ec2", "vm"):
            template["Resources"][rid] = {"Type": "AWS::EC2::Instance", "Properties": {"ImageId": r.get("ami", "ami-0c55b159cbfafe1f0"), "InstanceType": r.get("size", "t3.micro")}}
        elif r.get("type") in ("db", "rds", "database"):
            template["Resources"][rid] = {"Type": "AWS::RDS::DBInstance", "Properties": {"Engine": r.get("engine", "postgres"), "DBInstanceClass": r.get("size", "db.t3.micro"), "AllocatedStorage": str(int(r.get("storage_gb", 20)))}}
    return {"ok": True, "stack": stack_name, "template": json.dumps(template, indent=2)}
def generate_k8s(app_name: str, image: str, replicas: int = 2, port: int = 80, service_type: str = "ClusterIP") -> dict:
    """Generate Deployment + Service Kubernetes manifests."""
    deployment = {
        "apiVersion": "apps/v1", "kind": "Deployment",
        "metadata": {"name": app_name, "labels": {"app": app_name}},
        "spec": {"replicas": replicas, "selector": {"matchLabels": {"app": app_name}},
                 "template": {"metadata": {"labels": {"app": app_name}},
                              "spec": {"containers": [{"name": app_name, "image": image, "ports": [{"containerPort": port}]}]}}}}
    service = {"apiVersion": "v1", "kind": "Service", "metadata": {"name": "%s-svc" % app_name},
               "spec": {"selector": {"app": app_name}, "ports": [{"port": port, "targetPort": port}], "type": service_type}}
    return {"ok": True, "manifests": [json.dumps(deployment, indent=2), json.dumps(service, indent=2)]}

def register_stack(stack_name: str, provider: str, manifest_hash: str = None, status: str = "planned") -> dict:
    state = _load()
    state["stacks"][stack_name] = {
        "provider": provider, "status": status,
        "hash": manifest_hash or hashlib.sha1(("%s%s" % (stack_name, time.time())).encode()).hexdigest()[:12],
        "updated_at": time.time(),
    }
    _save(state)
    return {"ok": True, "stack": stack_name, "record": state["stacks"][stack_name]}

def stack_status(stack_name: str = None) -> dict:
    state = _load()
    if stack_name:
        record = state["stacks"].get(stack_name)
        return {"ok": bool(record), "stack": stack_name, "record": record}
    return {"ok": True, "stacks": state["stacks"]}

def infra_tool(args: dict) -> dict:
    a = args or {}
    action = a.get("action", "")
    if action == "terraform":
        return generate_terraform(a.get("provider", "aws"), a.get("region", "us-east-1"), a.get("resources", []), a.get("stack_name", "friday_stack"))
    if action == "cloudformation":
        return generate_cloudformation(a.get("stack_name", "friday_stack"), a.get("resources", []))
    if action == "kubernetes":
        return generate_k8s(a.get("app_name", "friday-app"), a.get("image", "nginx:latest"), int(a.get("replicas", 2)), int(a.get("port", 80)), a.get("service_type", "ClusterIP"))
    if action == "register":
        return register_stack(a.get("stack_name", ""), a.get("provider", "aws"), a.get("manifest_hash"), a.get("status", "planned"))
    if action == "status":
        return stack_status(a.get("stack_name"))
    return {"ok": False, "error": "Unknown infra action. Use: terraform, cloudformation, kubernetes, register, status"}